export type Product = {
  id: string;
  name: string;
  description: string;
  price: number;
  imageUrl: string;
  currency: string;
  tags: string[];
};

export type ExtendedProduct = {
  id: string;
  name: string;
  title: string;
  description: string;
  price: number;
  imageUrl: string;
  currency: string;
  tags: string[];
};

export const PRODUCTS: Product[] = [];

// export const PRODUCTS: Product[] = [
//   {
//     id: "p0",
//     name: 'Budget Laptop 13"',
//     description:
//       "13-inch lightweight laptop with Intel i3, 4GB RAM and 128GB SSD, ideal for basic office work and students.",
//     price: 22000,
//     currency: "INR",
//     tags: [
//       "category:laptop",
//       "segment:budget",
//       "use:student",
//       "screen:13-inch",
//       "cpu:intel-i3",
//       "ram:4GB",
//       "storage:128GB-SSD",
//       "brand:Generic",
//       "os:windows",
//       "weight:light",
//     ],
//     imageUrl: "https://i.pinimg.com/736x/20/ca/a3/20caa341782a8c576064f4c9ce6fd61a.jpg",
//   },
//   {
//     id: "p1",
//     name: 'Budget Laptop 14"',
//     description:
//       "14-inch everyday laptop with Intel i3, 8GB RAM and 256GB SSD, good for browsing, docs and light tasks.",
//     price: 26000,
//     currency: "INR",
//     tags: [
//       "category:laptop",
//       "segment:budget",
//       "use:student",
//       "screen:14-inch",
//       "cpu:intel-i3",
//       "ram:8GB",
//       "storage:256GB-SSD",
//       "brand:Generic",
//       "os:windows",
//     ],
//     imageUrl: "https://i.pinimg.com/736x/20/ca/a3/20caa341782a8c576064f4c9ce6fd61a.jpg"
//   },
//   {
//     id: "p2",
//     name: 'Budget Laptop 15"',
//     description:
//       "15.6-inch laptop with Intel i5, 8GB RAM and 256GB SSD, suitable for office work and light multitasking.",
//     price: 35000,
//     currency: "INR",
//     tags: [
//       "category:laptop",
//       "segment:budget",
//       "use:office",
//       "screen:15.6-inch",
//       "cpu:intel-i5",
//       "ram:8GB",
//       "storage:256GB-SSD",
//       "brand:Generic",
//       "os:windows",
//     ],
//     imageUrl: "https://i.pinimg.com/736x/20/ca/a3/20caa341782a8c576064f4c9ce6fd61a.jpg"
//   },
//   {
//     id: "p3",
//     name: 'Student Laptop 15" Plus',
//     description:
//       "15-inch student laptop with AMD Ryzen 3, 8GB RAM and 512GB SSD, great for online classes and projects.",
//     price: 38000,
//     currency: "INR",
//     tags: [
//       "category:laptop",
//       "segment:budget",
//       "use:student",
//       "screen:15-inch",
//       "cpu:ryzen-3",
//       "ram:8GB",
//       "storage:512GB-SSD",
//       "brand:EduTech",
//       "os:windows",
//     ],
//     imageUrl: "https://i.pinimg.com/736x/20/ca/a3/20caa341782a8c576064f4c9ce6fd61a.jpg"
//   },
//   {
//     id: "p4",
//     name: 'Office Laptop 14" Pro',
//     description:
//       "14-inch business laptop with Intel i5, 16GB RAM and 512GB SSD, ideal for productivity and multitasking.",
//     price: 52000,
//     currency: "INR",
//     tags: [
//       "category:laptop",
//       "segment:midrange",
//       "use:office",
//       "screen:14-inch",
//       "cpu:intel-i5",
//       "ram:16GB",
//       "storage:512GB-SSD",
//       "brand:BizBook",
//       "os:windows",
//     ],
//     imageUrl: "https://i.pinimg.com/736x/20/ca/a3/20caa341782a8c576064f4c9ce6fd61a.jpg"
//   },
//   {
//     id: "p5",
//     name: 'Ultrabook 13" Air',
//     description:
//       "13-inch ultrabook with Intel i5, 16GB RAM and 512GB SSD, 1.1kg weight, perfect for travel and remote work.",
//     price: 90000,
//     currency: "INR",
//     tags: [
//       "category:laptop",
//       "segment:premium",
//       "use:travel",
//       "screen:13-inch",
//       "cpu:intel-i5",
//       "ram:16GB",
//       "storage:512GB-SSD",
//       "brand:LiteBook",
//       "weight:1.1kg",
//       "battery:long-life",
//     ],
//     imageUrl: "https://i.pinimg.com/736x/20/ca/a3/20caa341782a8c576064f4c9ce6fd61a.jpg"
//   },
//   {
//     id: "p6",
//     name: 'Creator Laptop 15"',
//     description:
//       "15.6-inch creator laptop with Intel i7, 16GB RAM, 1TB SSD and dedicated GPU, great for video editing and design.",
//     price: 115000,
//     currency: "INR",
//     tags: [
//       "category:laptop",
//       "segment:creator",
//       "use:video-editing",
//       "screen:15.6-inch",
//       "cpu:intel-i7",
//       "ram:16GB",
//       "storage:1TB-SSD",
//       "gpu:discrete",
//       "brand:CreatePro",
//     ],
//     imageUrl: "https://i.pinimg.com/736x/20/ca/a3/20caa341782a8c576064f4c9ce6fd61a.jpg"
//   },
//   {
//     id: "p7",
//     name: 'Gaming Laptop 15" RTX',
//     description:
//       "15.6-inch gaming laptop with Ryzen 5, 16GB RAM, 512GB SSD and RTX 3050 GPU for 1080p gaming.",
//     price: 78000,
//     currency: "INR",
//     tags: [
//       "category:laptop",
//       "segment:gaming",
//       "use:gaming",
//       "screen:15.6-inch",
//       "cpu:ryzen-5",
//       "ram:16GB",
//       "storage:512GB-SSD",
//       "gpu:rtx-3050",
//       "brand:GameMax",
//     ],
//     imageUrl: "https://i.pinimg.com/736x/20/ca/a3/20caa341782a8c576064f4c9ce6fd61a.jpg"
//   },
//   {
//     id: "p8",
//     name: 'Gaming Laptop 17"',
//     description:
//       "17-inch gaming laptop with Intel i7, 16GB RAM, 1TB SSD and RTX 3060, large screen for immersive gameplay.",
//     price: 118000,
//     currency: "INR",
//     tags: [
//       "category:laptop",
//       "segment:gaming",
//       "use:gaming",
//       "screen:17-inch",
//       "cpu:intel-i7",
//       "ram:16GB",
//       "storage:1TB-SSD",
//       "gpu:rtx-3060",
//       "brand:GameMax",
//     ],
//     imageUrl: "https://i.pinimg.com/736x/20/ca/a3/20caa341782a8c576064f4c9ce6fd61a.jpg"
//   },
//   {
//     id: "p9",
//     name: 'Student Chromebook 11"',
//     description:
//       "11.6-inch Chromebook with 4GB RAM and 64GB storage, ideal for web apps and classroom use.",
//     price: 19000,
//     currency: "INR",
//     tags: [
//       "category:laptop",
//       "segment:budget",
//       "use:student",
//       "screen:11.6-inch",
//       "cpu:celeron",
//       "ram:4GB",
//       "storage:64GB-emmc",
//       "os:chromeos",
//       "brand:EduTech",
//     ],
//     imageUrl: "https://i.pinimg.com/736x/20/ca/a3/20caa341782a8c576064f4c9ce6fd61a.jpg"
//   },
//   {
//     id: "p10",
//     name: '2-in-1 Touch Laptop 14"',
//     description:
//       "Convertible 14-inch touchscreen laptop with Ryzen 5, 8GB RAM and 512GB SSD, supports pen input.",
//     price: 65000,
//     currency: "INR",
//     tags: [
//       "category:laptop",
//       "segment:midrange",
//       "use:notes",
//       "formfactor:2-in-1",
//       "screen:14-inch-touch",
//       "cpu:ryzen-5",
//       "ram:8GB",
//       "storage:512GB-SSD",
//       "brand:FlexBook",
//     ],
//     imageUrl: "https://i.pinimg.com/736x/20/ca/a3/20caa341782a8c576064f4c9ce6fd61a.jpg"
//   },
//   {
//     id: "p11",
//     name: 'Business Ultrabook 14"',
//     description:
//       "Slim 14-inch business ultrabook with Intel i7, 16GB RAM, 512GB SSD and fingerprint reader.",
//     price: 105000,
//     currency: "INR",
//     tags: [
//       "category:laptop",
//       "segment:premium",
//       "use:office",
//       "screen:14-inch",
//       "cpu:intel-i7",
//       "ram:16GB",
//       "storage:512GB-SSD",
//       "security:fingerprint",
//       "brand:BizBook",
//     ],
//     imageUrl: "https://i.pinimg.com/736x/20/ca/a3/20caa341782a8c576064f4c9ce6fd61a.jpg"
//   },
//   {
//     id: "p12",
//     name: 'Entry Laptop 15" HDD',
//     description:
//       "15.6-inch entry-level laptop with 8GB RAM and 1TB HDD, suitable for basic tasks and media.",
//     price: 28000,
//     currency: "INR",
//     tags: [
//       "category:laptop",
//       "segment:budget",
//       "use:home",
//       "screen:15.6-inch",
//       "ram:8GB",
//       "storage:1TB-HDD",
//       "brand:HomeBook",
//       "os:windows",
//     ],
//     imageUrl: "https://i.pinimg.com/736x/20/ca/a3/20caa341782a8c576064f4c9ce6fd61a.jpg"
//   },
//   {
//     id: "p13",
//     name: 'Coding Laptop 15"',
//     description:
//       "15.6-inch laptop with Ryzen 5, 16GB RAM and 512GB SSD, ideal for programming and local development.",
//     price: 58000,
//     currency: "INR",
//     tags: [
//       "category:laptop",
//       "segment:midrange",
//       "use:coding",
//       "screen:15.6-inch",
//       "cpu:ryzen-5",
//       "ram:16GB",
//       "storage:512GB-SSD",
//       "brand:DevBox",
//     ],
//     imageUrl: "https://i.pinimg.com/736x/20/ca/a3/20caa341782a8c576064f4c9ce6fd61a.jpg"
//   },
//   {
//     id: "p14",
//     name: 'Developer Laptop 14" Pro',
//     description:
//       "Compact 14-inch developer laptop with Intel i7, 32GB RAM and 1TB SSD, perfect for heavy IDEs and containers.",
//     price: 135000,
//     currency: "INR",
//     tags: [
//       "category:laptop",
//       "segment:creator",
//       "use:coding",
//       "screen:14-inch",
//       "cpu:intel-i7",
//       "ram:32GB",
//       "storage:1TB-SSD",
//       "brand:DevBox",
//     ],
//     imageUrl: "https://i.pinimg.com/736x/20/ca/a3/20caa341782a8c576064f4c9ce6fd61a.jpg"
//   },
//   {
//     id: "p15",
//     name: 'Budget Laptop 16"',
//     description:
//       "16-inch display laptop with Intel i5, 8GB RAM and 512GB SSD, good for media consumption and browsing.",
//     price: 42000,
//     currency: "INR",
//     tags: [
//       "category:laptop",
//       "segment:budget",
//       "use:media",
//       "screen:16-inch",
//       "cpu:intel-i5",
//       "ram:8GB",
//       "storage:512GB-SSD",
//       "brand:Generic",
//     ],
//     imageUrl: "https://i.pinimg.com/736x/20/ca/a3/20caa341782a8c576064f4c9ce6fd61a.jpg"
//   },
//   {
//     id: "p16",
//     name: 'Gaming Laptop 15" Budget',
//     description:
//       "Affordable 15-inch gaming laptop with GTX 1650, Ryzen 5, 8GB RAM and 512GB SSD.",
//     price: 64000,
//     currency: "INR",
//     tags: [
//       "category:laptop",
//       "segment:gaming",
//       "use:gaming",
//       "screen:15.6-inch",
//       "cpu:ryzen-5",
//       "ram:8GB",
//       "storage:512GB-SSD",
//       "gpu:gtx-1650",
//       "brand:GameLite",
//     ],
//     imageUrl: "https://i.pinimg.com/736x/20/ca/a3/20caa341782a8c576064f4c9ce6fd61a.jpg"
//   },
//   {
//     id: "p17",
//     name: 'Creator Laptop 14" OLED',
//     description:
//       "14-inch OLED creator laptop with Intel i7, 16GB RAM and 1TB SSD, excellent color accuracy for designers.",
//     price: 145000,
//     currency: "INR",
//     tags: [
//       "category:laptop",
//       "segment:creator",
//       "use:design",
//       "screen:14-inch-oled",
//       "cpu:intel-i7",
//       "ram:16GB",
//       "storage:1TB-SSD",
//       "brand:CreatePro",
//     ],
//     imageUrl: "https://i.pinimg.com/736x/20/ca/a3/20caa341782a8c576064f4c9ce6fd61a.jpg"
//   },
//   {
//     id: "p18",
//     name: 'Student Laptop 14" Thin',
//     description:
//       "Thin 14-inch laptop with Intel i3, 8GB RAM and 256GB SSD for college students.",
//     price: 31000,
//     currency: "INR",
//     tags: [
//       "category:laptop",
//       "segment:budget",
//       "use:student",
//       "screen:14-inch",
//       "cpu:intel-i3",
//       "ram:8GB",
//       "storage:256GB-SSD",
//       "brand:EduTech",
//     ],
//     imageUrl: "https://i.pinimg.com/736x/20/ca/a3/20caa341782a8c576064f4c9ce6fd61a.jpg"
//   },
//   {
//     id: "p19",
//     name: 'Office Laptop 15" Secure',
//     description:
//       "15.6-inch office laptop with Intel i5, 16GB RAM, 512GB SSD and TPM security chip.",
//     price: 65000,
//     currency: "INR",
//     tags: [
//       "category:laptop",
//       "segment:midrange",
//       "use:office",
//       "screen:15.6-inch",
//       "cpu:intel-i5",
//       "ram:16GB",
//       "storage:512GB-SSD",
//       "security:tpm",
//       "brand:BizBook",
//     ],
//     imageUrl: "https://i.pinimg.com/736x/20/ca/a3/20caa341782a8c576064f4c9ce6fd61a.jpg"
//   },

//   // Smartphones p20–p39
//   {
//     id: "p20",
//     name: "Budget Smartphone 64GB",
//     description:
//       "6.5-inch HD+ budget smartphone with 4GB RAM and 64GB storage, 5000mAh battery.",
//     price: 11000,
//     currency: "INR",
//     tags: [
//       "category:smartphone",
//       "segment:budget",
//       "use:everyday",
//       "screen:6.5-inch",
//       "ram:4GB",
//       "storage:64GB",
//       "battery:5000mAh",
//       "camera:13MP",
//       "brand:AlphaMobile",
//     ],
//     imageUrl: "https://i.pinimg.com/1200x/86/ee/a4/86eea494260892cc0fbc8347b2124af3.jpg",
//   },
//   {
//     id: "p21",
//     name: "Budget Smartphone 128GB",
//     description:
//       "6.6-inch FHD+ phone with 6GB RAM and 128GB storage, 50MP triple camera.",
//     price: 15000,
//     currency: "INR",
//     tags: [
//       "category:smartphone",
//       "segment:budget",
//       "use:camera",
//       "screen:6.6-inch",
//       "ram:6GB",
//       "storage:128GB",
//       "battery:5000mAh",
//       "camera:50MP",
//       "brand:AlphaMobile",
//     ],
//     imageUrl: "https://i.pinimg.com/1200x/86/ee/a4/86eea494260892cc0fbc8347b2124af3.jpg",
//   },
//   {
//     id: "p22",
//     name: "5G Midrange Phone",
//     description:
//       "6.4-inch AMOLED 90Hz display, 8GB RAM, 128GB storage, 5G support and 64MP camera.",
//     price: 26000,
//     currency: "INR",
//     tags: [
//       "category:smartphone",
//       "segment:midrange",
//       "use:5g",
//       "screen:6.4-inch-amoled",
//       "ram:8GB",
//       "storage:128GB",
//       "battery:4500mAh",
//       "camera:64MP",
//       "brand:SkyPhone",
//     ],
//     imageUrl: "https://i.pinimg.com/1200x/86/ee/a4/86eea494260892cc0fbc8347b2124af3.jpg",
//   },
//   {
//     id: "p23",
//     name: "Camera Phone 108MP",
//     description:
//       "6.7-inch AMOLED phone with 108MP main camera, 8GB RAM, 256GB storage and OIS.",
//     price: 34000,
//     currency: "INR",
//     tags: [
//       "category:smartphone",
//       "segment:midrange",
//       "use:photography",
//       "screen:6.7-inch-amoled",
//       "ram:8GB",
//       "storage:256GB",
//       "camera:108MP",
//       "brand:SkyPhone",
//     ],
//     imageUrl: "https://i.pinimg.com/1200x/86/ee/a4/86eea494260892cc0fbc8347b2124af3.jpg",
//   },
//   {
//     id: "p24",
//     name: 'Compact Smartphone 5.8"',
//     description:
//       "5.8-inch compact phone with 6GB RAM, 128GB storage and good one-handed usability.",
//     price: 27000,
//     currency: "INR",
//     tags: [
//       "category:smartphone",
//       "segment:midrange",
//       "use:compact",
//       "screen:5.8-inch",
//       "ram:6GB",
//       "storage:128GB",
//       "brand:PocketPhone",
//     ],
//     imageUrl: "https://i.pinimg.com/1200x/86/ee/a4/86eea494260892cc0fbc8347b2124af3.jpg",
//   },
//   {
//     id: "p25",
//     name: "Flagship Smartphone Pro",
//     description:
//       "6.8-inch QHD+ flagship with 12GB RAM, 256GB storage, Snapdragon 8 series and triple camera.",
//     price: 78000,
//     currency: "INR",
//     tags: [
//       "category:smartphone",
//       "segment:premium",
//       "use:flagship",
//       "screen:6.8-inch",
//       "ram:12GB",
//       "storage:256GB",
//       "chipset:flagship",
//       "brand:ZenMobile",
//     ],
//     imageUrl: "https://i.pinimg.com/1200x/86/ee/a4/86eea494260892cc0fbc8347b2124af3.jpg",
//   },
//   {
//     id: "p26",
//     name: "Gaming Phone 120Hz",
//     description:
//       "6.7-inch 120Hz phone with 12GB RAM, 256GB storage and dedicated gaming mode.",
//     price: 42000,
//     currency: "INR",
//     tags: [
//       "category:smartphone",
//       "segment:gaming",
//       "use:gaming",
//       "screen:6.7-inch-120hz",
//       "ram:12GB",
//       "storage:256GB",
//       "battery:6000mAh",
//       "brand:GamePhone",
//     ],
//     imageUrl: "https://i.pinimg.com/1200x/86/ee/a4/86eea494260892cc0fbc8347b2124af3.jpg",
//   },
//   {
//     id: "p27",
//     name: "Battery King 7000mAh",
//     description:
//       "6.8-inch phone with 7000mAh battery and 8GB RAM, designed for heavy users and travelers.",
//     price: 23000,
//     currency: "INR",
//     tags: [
//       "category:smartphone",
//       "segment:midrange",
//       "use:battery-life",
//       "screen:6.8-inch",
//       "ram:8GB",
//       "storage:128GB",
//       "battery:7000mAh",
//       "brand:PowerPhone",
//     ],
//     imageUrl: "https://i.pinimg.com/1200x/86/ee/a4/86eea494260892cc0fbc8347b2124af3.jpg",
//   },
//   {
//     id: "p28",
//     name: "Student 4G Smartphone",
//     description:
//       "Simple 4G smartphone with 3GB RAM and 32GB storage, ideal for online classes and messaging.",
//     price: 8500,
//     currency: "INR",
//     tags: [
//       "category:smartphone",
//       "segment:budget",
//       "use:student",
//       "screen:6.1-inch",
//       "ram:3GB",
//       "storage:32GB",
//       "brand:EduMobile",
//     ],
//     imageUrl: "https://i.pinimg.com/1200x/86/ee/a4/86eea494260892cc0fbc8347b2124af3.jpg",
//   },
//   {
//     id: "p29",
//     name: "Photography Phone Lite",
//     description:
//       "Quad camera phone with 48MP main sensor, 6GB RAM and 128GB storage.",
//     price: 19000,
//     currency: "INR",
//     tags: [
//       "category:smartphone",
//       "segment:budget",
//       "use:photography",
//       "screen:6.5-inch",
//       "ram:6GB",
//       "storage:128GB",
//       "camera:48MP",
//       "brand:PhotoLite",
//     ],
//     imageUrl: "https://i.pinimg.com/1200x/86/ee/a4/86eea494260892cc0fbc8347b2124af3.jpg",
//   },
//   {
//     id: "p30",
//     name: "5G Compact Pro",
//     description:
//       "5G-ready compact phone with 8GB RAM, 256GB storage and dual stereo speakers.",
//     price: 38000,
//     currency: "INR",
//     tags: [
//       "category:smartphone",
//       "segment:midrange",
//       "use:5g",
//       "use:compact",
//       "screen:6-inch",
//       "ram:8GB",
//       "storage:256GB",
//       "brand:PocketPhone",
//     ],
//     imageUrl: "https://i.pinimg.com/1200x/86/ee/a4/86eea494260892cc0fbc8347b2124af3.jpg",
//   },
//   {
//     id: "p31",
//     name: "Foldable Phone Mini",
//     description:
//       "Small foldable phone with 8GB RAM and 256GB storage, premium look and feel.",
//     price: 98000,
//     currency: "INR",
//     tags: [
//       "category:smartphone",
//       "segment:premium",
//       "use:foldable",
//       "ram:8GB",
//       "storage:256GB",
//       "brand:FlexPhone",
//     ],
//     imageUrl: "https://i.pinimg.com/1200x/86/ee/a4/86eea494260892cc0fbc8347b2124af3.jpg",
//   },
//   {
//     id: "p32",
//     name: "Flagship Camera Phone Ultra",
//     description:
//       "Top-end camera phone with 200MP main sensor, 12GB RAM and 512GB storage.",
//     price: 95000,
//     currency: "INR",
//     tags: [
//       "category:smartphone",
//       "segment:premium",
//       "use:photography",
//       "ram:12GB",
//       "storage:512GB",
//       "camera:200MP",
//       "brand:ZenMobile",
//     ],
//     imageUrl: "https://i.pinimg.com/1200x/86/ee/a4/86eea494260892cc0fbc8347b2124af3.jpg",
//   },
//   {
//     id: "p33",
//     name: "Rugged Outdoor Phone",
//     description:
//       "IP68 water- and dust-resistant phone with 6GB RAM and 128GB storage, built for outdoor use.",
//     price: 29000,
//     currency: "INR",
//     tags: [
//       "category:smartphone",
//       "segment:midrange",
//       "use:rugged",
//       "durability:ip68",
//       "ram:6GB",
//       "storage:128GB",
//       "brand:TrailPhone",
//     ],
//     imageUrl: "https://i.pinimg.com/1200x/86/ee/a4/86eea494260892cc0fbc8347b2124af3.jpg",
//   },
//   {
//     id: "p34",
//     name: "Senior-Friendly Smartphone",
//     description:
//       "Phone with large icons, simple UI, 4GB RAM and 64GB storage, ideal for seniors.",
//     price: 13000,
//     currency: "INR",
//     tags: [
//       "category:smartphone",
//       "segment:budget",
//       "use:senior",
//       "screen:6-inch",
//       "ram:4GB",
//       "storage:64GB",
//       "brand:EasyPhone",
//     ],
//     imageUrl: "https://i.pinimg.com/1200x/86/ee/a4/86eea494260892cc0fbc8347b2124af3.jpg",
//   },
//   {
//     id: "p35",
//     name: "Student 5G Phone",
//     description:
//       "Affordable 5G phone with 6GB RAM, 128GB storage and 5000mAh battery for students.",
//     price: 19000,
//     currency: "INR",
//     tags: [
//       "category:smartphone",
//       "segment:budget",
//       "use:student",
//       "use:5g",
//       "ram:6GB",
//       "storage:128GB",
//       "battery:5000mAh",
//       "brand:EduMobile",
//     ],
//     imageUrl: "https://i.pinimg.com/1200x/86/ee/a4/86eea494260892cc0fbc8347b2124af3.jpg",
//   },
//   {
//     id: "p36",
//     name: "Music Lover Smartphone",
//     description:
//       "Phone with dual stereo speakers, Hi-Res audio support, 6GB RAM and 128GB storage.",
//     price: 21000,
//     currency: "INR",
//     tags: [
//       "category:smartphone",
//       "segment:midrange",
//       "use:music",
//       "audio:stereo-speakers",
//       "ram:6GB",
//       "storage:128GB",
//       "brand:SoundPhone",
//     ],
//     imageUrl: "https://i.pinimg.com/1200x/86/ee/a4/86eea494260892cc0fbc8347b2124af3.jpg",
//   },
//   {
//     id: "p37",
//     name: "Entry 5G Phone",
//     description:
//       "Cheapest 5G device in lineup with 4GB RAM and 64GB storage, basic cameras and big battery.",
//     price: 16000,
//     currency: "INR",
//     tags: [
//       "category:smartphone",
//       "segment:budget",
//       "use:5g",
//       "ram:4GB",
//       "storage:64GB",
//       "battery:5000mAh",
//       "brand:AlphaMobile",
//     ],
//     imageUrl: "https://i.pinimg.com/1200x/86/ee/a4/86eea494260892cc0fbc8347b2124af3.jpg",
//   },
//   {
//     id: "p38",
//     name: "Ultra Battery Phone 8000mAh",
//     description:
//       "Massive 8000mAh battery phone with 6GB RAM, ideal as a backup or travel device.",
//     price: 24000,
//     currency: "INR",
//     tags: [
//       "category:smartphone",
//       "segment:midrange",
//       "use:battery-life",
//       "battery:8000mAh",
//       "ram:6GB",
//       "storage:128GB",
//       "brand:PowerPhone",
//     ],
//     imageUrl: "https://i.pinimg.com/1200x/86/ee/a4/86eea494260892cc0fbc8347b2124af3.jpg",
//   },
//   {
//     id: "p39",
//     name: "Budget Camera Phone 50MP",
//     description:
//       "Budget phone with 50MP main camera, 4GB RAM and 64GB storage, value for money.",
//     price: 12000,
//     currency: "INR",
//     tags: [
//       "category:smartphone",
//       "segment:budget",
//       "use:photography",
//       "camera:50MP",
//       "ram:4GB",
//       "storage:64GB",
//       "brand:PhotoLite",
//     ],
//     imageUrl: "https://i.pinimg.com/1200x/86/ee/a4/86eea494260892cc0fbc8347b2124af3.jpg",
//   },

//   // Audio p40–p59
//   {
//     id: "p40",
//     name: "Budget Wired Earphones",
//     description:
//       "In-ear wired earphones with mic, suitable for calls and casual music.",
//     price: 499,
//     currency: "INR",
//     tags: [
//       "category:audio",
//       "type:wired-earphones",
//       "segment:budget",
//       "use:calls",
//       "brand:SoundCore",
//     ],
//     imageUrl: "https://i.pinimg.com/736x/73/6f/2b/736f2b53823f2a90436036ee247338c2.jpg",
//   },
//   {
//     id: "p41",
//     name: "Wireless Neckband Earphones",
//     description: "Bluetooth neckband with 12-hour battery life and sweat resistance.",
//     price: 1599,
//     currency: "INR",
//     tags: [
//       "category:audio",
//       "type:neckband",
//       "segment:budget",
//       "use:commute",
//       "battery:12h",
//       "brand:SoundCore",
//     ],
//     imageUrl: "https://i.pinimg.com/736x/73/6f/2b/736f2b53823f2a90436036ee247338c2.jpg",
//   },
//   {
//     id: "p42",
//     name: "True Wireless Earbuds Basic",
//     description: "TWS earbuds with 20-hour total playback and touch controls.",
//     price: 1999,
//     currency: "INR",
//     tags: [
//       "category:audio",
//       "type:tws-earbuds",
//       "segment:budget",
//       "use:everyday",
//       "battery:20h",
//       "brand:AirBeats",
//     ],
//     imageUrl: "https://i.pinimg.com/736x/73/6f/2b/736f2b53823f2a90436036ee247338c2.jpg",
//   },
//   {
//     id: "p43",
//     name: "True Wireless Earbuds ANC",
//     description: "ANC earbuds with 30-hour total playback and wireless charging case.",
//     price: 5999,
//     currency: "INR",
//     tags: [
//       "category:audio",
//       "type:tws-earbuds",
//       "segment:midrange",
//       "feature:anc",
//       "battery:30h",
//       "brand:AirBeats",
//     ],
//     imageUrl: "https://i.pinimg.com/736x/73/6f/2b/736f2b53823f2a90436036ee247338c2.jpg",
//   },
//   {
//     id: "p44",
//     name: "Gaming Headset Wired",
//     description: "Over-ear gaming headset with boom mic and 7.1 surround sound.",
//     price: 3499,
//     currency: "INR",
//     tags: [
//       "category:audio",
//       "type:gaming-headset",
//       "segment:midrange",
//       "use:gaming",
//       "brand:GameSound",
//     ],
//     imageUrl: "https://i.pinimg.com/736x/73/6f/2b/736f2b53823f2a90436036ee247338c2.jpg",
//   },
//   {
//     id: "p45",
//     name: "Studio Monitor Headphones",
//     description: "Closed-back studio headphones for mixing and monitoring.",
//     price: 7800,
//     currency: "INR",
//     tags: [
//       "category:audio",
//       "type:studio-headphones",
//       "segment:creator",
//       "use:music-production",
//       "brand:ProSound",
//     ],
//     imageUrl: "https://i.pinimg.com/736x/73/6f/2b/736f2b53823f2a90436036ee247338c2.jpg",
//   },
//   {
//     id: "p46",
//     name: "Over-Ear Bluetooth Headphones",
//     description: "Wireless over-ear headphones with 40-hour battery life.",
//     price: 3999,
//     currency: "INR",
//     tags: [
//       "category:audio",
//       "type:over-ear",
//       "segment:midrange",
//       "battery:40h",
//       "use:travel",
//       "brand:SoundCore",
//     ],
//     imageUrl: "https://i.pinimg.com/736x/73/6f/2b/736f2b53823f2a90436036ee247338c2.jpg",
//   },
//   {
//     id: "p47",
//     name: "Premium ANC Headphones",
//     description:
//       "Flagship over-ear ANC headphones with LDAC and transparency mode.",
//     price: 18999,
//     currency: "INR",
//     tags: [
//       "category:audio",
//       "type:over-ear",
//       "segment:premium",
//       "feature:anc",
//       "feature:ldac",
//       "brand:ProSound",
//     ],
//     imageUrl: "https://i.pinimg.com/736x/73/6f/2b/736f2b53823f2a90436036ee247338c2.jpg",
//   },
//   {
//     id: "p48",
//     name: "Sports TWS Earbuds",
//     description: "TWS earbuds with ear hooks, IPX5 rating and bass-heavy sound.",
//     price: 3499,
//     currency: "INR",
//     tags: [
//       "category:audio",
//       "type:tws-earbuds",
//       "segment:midrange",
//       "use:sports",
//       "durability:ipx5",
//       "brand:FitBeats",
//     ],
//     imageUrl: "https://i.pinimg.com/736x/73/6f/2b/736f2b53823f2a90436036ee247338c2.jpg",
//   },
//   {
//     id: "p49",
//     name: "Kids Safe Headphones",
//     description: "Volume-limited on-ear headphones safe for kids.",
//     price: 1499,
//     currency: "INR",
//     tags: [
//       "category:audio",
//       "type:on-ear",
//       "segment:budget",
//       "use:kids",
//       "brand:KidSound",
//     ],
//     imageUrl: "https://i.pinimg.com/736x/73/6f/2b/736f2b53823f2a90436036ee247338c2.jpg",
//   },
//   {
//     id: "p50",
//     name: "Conference Speakerphone",
//     description: "USB/Bluetooth conference speaker for meetings.",
//     price: 8999,
//     currency: "INR",
//     tags: [
//       "category:audio",
//       "type:speakerphone",
//       "segment:office",
//       "use:meetings",
//       "brand:BizAudio",
//     ],
//     imageUrl: "https://i.pinimg.com/736x/73/6f/2b/736f2b53823f2a90436036ee247338c2.jpg",
//   },
//   {
//     id: "p51",
//     name: "Portable Bluetooth Speaker",
//     description: "IPX7 waterproof portable speaker with 24-hour battery life.",
//     price: 3999,
//     currency: "INR",
//     tags: [
//       "category:audio",
//       "type:bluetooth-speaker",
//       "segment:midrange",
//       "use:outdoor",
//       "battery:24h",
//       "durability:ipx7",
//       "brand:PartyBox",
//     ],
//     imageUrl: "https://i.pinimg.com/1200x/10/82/d6/1082d67a4cf6094515b4339ae9b9d5ef.jpg",
//   },
//   {
//     id: "p52",
//     name: "Mini Bluetooth Speaker",
//     description: "Compact speaker with 10-hour battery, pocket friendly.",
//     price: 1499,
//     currency: "INR",
//     tags: [
//       "category:audio",
//       "type:bluetooth-speaker",
//       "segment:budget",
//       "use:portable",
//       "battery:10h",
//       "brand:MiniSound",
//     ],
//     imageUrl: "https://i.pinimg.com/1200x/10/82/d6/1082d67a4cf6094515b4339ae9b9d5ef.jpg",
//   },
//   {
//     id: "p53",
//     name: "Soundbar 2.1 Channel",
//     description: "2.1 soundbar with wired subwoofer for TVs.",
//     price: 7999,
//     currency: "INR",
//     tags: [
//       "category:audio",
//       "type:soundbar",
//       "segment:midrange",
//       "use:tv",
//       "brand:HomeCinema",
//     ],
//     imageUrl: "https://i.pinimg.com/1200x/10/82/d6/1082d67a4cf6094515b4339ae9b9d5ef.jpg",
//   },
//   {
//     id: "p54",
//     name: "Dolby Atmos Soundbar",
//     description: "Premium soundbar with Dolby Atmos and wireless subwoofer.",
//     price: 25999,
//     currency: "INR",
//     tags: [
//       "category:audio",
//       "type:soundbar",
//       "segment:premium",
//       "feature:dolby-atmos",
//       "use:home-theater",
//       "brand:HomeCinema",
//     ],
//     imageUrl: "https://i.pinimg.com/1200x/10/82/d6/1082d67a4cf6094515b4339ae9b9d5ef.jpg",
//   },
//   {
//     id: "p55",
//     name: "Hi-Res Wired Headphones",
//     description: "Over-ear Hi-Res certified wired headphones for audiophiles.",
//     price: 10999,
//     currency: "INR",
//     tags: [
//       "category:audio",
//       "type:over-ear",
//       "segment:premium",
//       "use:audiophile",
//       "brand:ProSound",
//     ],
//     imageUrl: "https://i.pinimg.com/1200x/10/82/d6/1082d67a4cf6094515b4339ae9b9d5ef.jpg",
//   },
//   {
//     id: "p56",
//     name: "USB-C Earphones",
//     description:
//       "In-ear USB-C wired earphones with mic, for phones without 3.5mm jack.",
//     price: 1299,
//     currency: "INR",
//     tags: [
//       "category:audio",
//       "type:wired-earphones",
//       "connector:usb-c",
//       "segment:budget",
//       "use:phone",
//       "brand:SoundCore",
//     ],
//     imageUrl: "https://i.pinimg.com/1200x/10/82/d6/1082d67a4cf6094515b4339ae9b9d5ef.jpg",
//   },
//   {
//     id: "p57",
//     name: "ANC Neckband Earphones",
//     description: "Neckband with active noise cancellation and 20-hour playback.",
//     price: 4499,
//     currency: "INR",
//     tags: [
//       "category:audio",
//       "type:neckband",
//       "feature:anc",
//       "segment:midrange",
//       "battery:20h",
//       "brand:AirBeats",
//     ],
//     imageUrl: "https://i.pinimg.com/1200x/10/82/d6/1082d67a4cf6094515b4339ae9b9d5ef.jpg",
//   },
//   {
//     id: "p58",
//     name: "Studio Monitor Speakers",
//     description: "Pair of 5-inch studio monitor speakers for mixing.",
//     price: 18999,
//     currency: "INR",
//     tags: [
//       "category:audio",
//       "type:studio-monitors",
//       "segment:creator",
//       "use:music-production",
//       "brand:ProSound",
//     ],
//     imageUrl: "https://i.pinimg.com/1200x/10/82/d6/1082d67a4cf6094515b4339ae9b9d5ef.jpg",
//   },
//   {
//     id: "p59",
//     name: "Gaming Soundbar RGB",
//     description:
//       "Compact gaming soundbar with RGB lighting and virtual surround sound.",
//     price: 3499,
//     currency: "INR",
//     tags: [
//       "category:audio",
//       "type:soundbar",
//       "segment:gaming",
//       "use:pc-gaming",
//       "feature:rgb",
//       "brand:GameSound",
//     ],
//     imageUrl: "https://i.pinimg.com/1200x/10/82/d6/1082d67a4cf6094515b4339ae9b9d5ef.jpg",
//   },

//   // Monitors & accessories p60–p79
//   {
//     id: "p60",
//     name: '24" 1080p Office Monitor',
//     description:
//       "24-inch IPS monitor with 1080p resolution and tilt stand.",
//     price: 9999,
//     currency: "INR",
//     tags: [
//       "category:monitor",
//       "segment:office",
//       "size:24-inch",
//       "resolution:1080p",
//       "panel:ips",
//       "brand:ViewPlus",
//     ],
//     imageUrl: "https://cdn.example.com/images/monitors/p60.jpg",
//   },
//   {
//     id: "p61",
//     name: '27" 144Hz Gaming Monitor',
//     description:
//       "27-inch 1080p gaming monitor with 144Hz refresh rate and 1ms response.",
//     price: 18999,
//     currency: "INR",
//     tags: [
//       "category:monitor",
//       "segment:gaming",
//       "size:27-inch",
//       "resolution:1080p",
//       "refresh:144hz",
//       "brand:GameView",
//     ],
//     imageUrl: "https://cdn.example.com/images/monitors/p61.jpg",
//   },
//   {
//     id: "p62",
//     name: '27" 2K Designer Monitor',
//     description:
//       "27-inch 1440p IPS monitor with wide color gamut for designers.",
//     price: 25999,
//     currency: "INR",
//     tags: [
//       "category:monitor",
//       "segment:creator",
//       "size:27-inch",
//       "resolution:1440p",
//       "panel:ips",
//       "use:design",
//       "brand:ViewPlus",
//     ],
//     imageUrl: "https://cdn.example.com/images/monitors/p62.jpg",
//   },
//   {
//     id: "p63",
//     name: '34" Ultrawide Monitor',
//     description:
//       "34-inch ultrawide monitor with 1440p resolution, great for productivity.",
//     price: 45999,
//     currency: "INR",
//     tags: [
//       "category:monitor",
//       "segment:premium",
//       "size:34-inch",
//       "resolution:1440p",
//       "format:ultrawide",
//       "brand:UltraView",
//     ],
//     imageUrl: "https://cdn.example.com/images/monitors/p63.jpg",
//   },
//   {
//     id: "p64",
//     name: 'Portable 15.6" USB-C Monitor',
//     description:
//       "Portable 15.6-inch USB-C monitor for laptop second screen.",
//     price: 17999,
//     currency: "INR",
//     tags: [
//       "category:monitor",
//       "segment:portable",
//       "size:15.6-inch",
//       "connector:usb-c",
//       "use:travel",
//       "brand:TravelView",
//     ],
//     imageUrl: "https://cdn.example.com/images/monitors/p64.jpg",
//   },
//   {
//     id: "p65",
//     name: '4K 27" Monitor',
//     description: "27-inch 4K UHD monitor with HDR support.",
//     price: 32999,
//     currency: "INR",
//     tags: [
//       "category:monitor",
//       "segment:premium",
//       "size:27-inch",
//       "resolution:4k",
//       "feature:hdr",
//       "brand:ViewPlus",
//     ],
//     imageUrl: "https://cdn.example.com/images/monitors/p65.jpg",
//   },
//   {
//     id: "p66",
//     name: "Gaming Mouse RGB",
//     description:
//       "Wired gaming mouse with 6 programmable buttons and RGB lighting.",
//     price: 1499,
//     currency: "INR",
//     tags: [
//       "category:accessory",
//       "type:mouse",
//       "segment:gaming",
//       "feature:rgb",
//       "brand:GameGear",
//     ],
//     imageUrl: "https://cdn.example.com/images/accessories/p66.jpg",
//   },
//   {
//     id: "p67",
//     name: "Mechanical Keyboard Blue Switches",
//     description:
//       "Full-size mechanical keyboard with clicky blue switches.",
//     price: 3999,
//     currency: "INR",
//     tags: [
//       "category:accessory",
//       "type:keyboard",
//       "segment:gaming",
//       "switches:blue",
//       "brand:KeyPro",
//     ],
//     imageUrl: "https://cdn.example.com/images/accessories/p67.jpg",
//   },
//   {
//     id: "p68",
//     name: "Wireless Mouse Silent",
//     description:
//       "Silent wireless mouse with 2.4GHz dongle, ideal for office.",
//     price: 899,
//     currency: "INR",
//     tags: [
//       "category:accessory",
//       "type:mouse",
//       "segment:office",
//       "feature:silent-clicks",
//       "brand:OfficeGear",
//     ],
//     imageUrl: "https://cdn.example.com/images/accessories/p68.jpg",
//   },
//   {
//     id: "p69",
//     name: "Laptop Cooling Pad",
//     description:
//       "Cooling pad with dual fans and adjustable angle for laptops up to 17 inches.",
//     price: 1499,
//     currency: "INR",
//     tags: [
//       "category:accessory",
//       "type:cooling-pad",
//       "use:laptop",
//       "brand:CoolGear",
//     ],
//     imageUrl: "https://cdn.example.com/images/accessories/p69.jpg",
//   },

//   // Storage & misc p70–p99
//   {
//     id: "p70",
//     name: "External SSD 500GB",
//     description:
//       "Portable USB-C external SSD with 500GB capacity and fast transfer speeds.",
//     price: 4999,
//     currency: "INR",
//     tags: [
//       "category:storage",
//       "type:ssd",
//       "capacity:500GB",
//       "connector:usb-c",
//       "brand:StoreFast",
//     ],
//     imageUrl: "https://cdn.example.com/images/storage/p70.jpg",
//   },
//   {
//     id: "p71",
//     name: "External SSD 1TB",
//     description: "1TB portable SSD with USB 3.2, ideal for backups and large files.",
//     price: 8999,
//     currency: "INR",
//     tags: [
//       "category:storage",
//       "type:ssd",
//       "capacity:1TB",
//       "connector:usb-3.2",
//       "brand:StoreFast",
//     ],
//     imageUrl: "https://cdn.example.com/images/storage/p71.jpg",
//   },
//   {
//     id: "p72",
//     name: "USB Flash Drive 64GB",
//     description: "Compact USB 3.0 flash drive with 64GB capacity.",
//     price: 699,
//     currency: "INR",
//     tags: [
//       "category:storage",
//       "type:usb-flash",
//       "capacity:64GB",
//       "connector:usb-3.0",
//       "brand:QuickStore",
//     ],
//     imageUrl: "https://cdn.example.com/images/storage/p72.jpg",
//   },
//   {
//     id: "p73",
//     name: "Portable HDD 1TB",
//     description: "1TB external hard drive with USB 3.0 interface.",
//     price: 3999,
//     currency: "INR",
//     tags: [
//       "category:storage",
//       "type:hdd",
//       "capacity:1TB",
//       "connector:usb-3.0",
//       "brand:DataBox",
//     ],
//     imageUrl: "https://cdn.example.com/images/storage/p73.jpg",
//   },
//   {
//     id: "p74",
//     name: "Portable HDD 2TB",
//     description: "2TB portable hard drive for backups and media storage.",
//     price: 5799,
//     currency: "INR",
//     tags: [
//       "category:storage",
//       "type:hdd",
//       "capacity:2TB",
//       "connector:usb-3.0",
//       "brand:DataBox",
//     ],
//     imageUrl: "https://cdn.example.com/images/storage/p74.jpg",
//   },
//   {
//     id: "p75",
//     name: 'Laptop Sleeve 13"',
//     description: "Protective neoprene sleeve for 13-inch laptops.",
//     price: 899,
//     currency: "INR",
//     tags: [
//       "category:accessory",
//       "type:laptop-sleeve",
//       "size:13-inch",
//       "brand:CarrySafe",
//     ],
//     imageUrl: "https://cdn.example.com/images/accessories/p75.jpg",
//   },
//   {
//     id: "p76",
//     name: 'Laptop Sleeve 15"',
//     description: "Stylish sleeve for 15.6-inch laptops with extra pocket.",
//     price: 1199,
//     currency: "INR",
//     tags: [
//       "category:accessory",
//       "type:laptop-sleeve",
//       "size:15.6-inch",
//       "brand:CarrySafe",
//     ],
//     imageUrl: "https://cdn.example.com/images/accessories/p76.jpg",
//   },
//   {
//     id: "p77",
//     name: "USB-C Hub 5-in-1",
//     description: "USB-C hub with HDMI, USB-A and card reader.",
//     price: 2499,
//     currency: "INR",
//     tags: [
//       "category:accessory",
//       "type:usb-hub",
//       "connector:usb-c",
//       "brand:ConnectPro",
//     ],
//     imageUrl: "https://cdn.example.com/images/accessories/p77.jpg",
//   },
//   {
//     id: "p78",
//     name: "USB-C Hub 8-in-1",
//     description: "8-in-1 USB-C hub with dual HDMI and Ethernet.",
//     price: 4299,
//     currency: "INR",
//     tags: [
//       "category:accessory",
//       "type:usb-hub",
//       "connector:usb-c",
//       "feature:ethernet",
//       "brand:ConnectPro",
//     ],
//     imageUrl: "https://cdn.example.com/images/accessories/p78.jpg",
//   },
//   {
//     id: "p79",
//     name: "Wireless Charging Pad",
//     description: "10W wireless charging pad compatible with most phones.",
//     price: 1499,
//     currency: "INR",
//     tags: [
//       "category:accessory",
//       "type:wireless-charger",
//       "use:phone",
//       "brand:ChargeEasy",
//     ],
//     imageUrl: "https://cdn.example.com/images/accessories/p79.jpg",
//   },
//   {
//     id: "p80",
//     name: "Mechanical Keyboard Brown Switches",
//     description: "Tenkeyless mechanical keyboard with tactile brown switches.",
//     price: 4499,
//     currency: "INR",
//     tags: [
//       "category:accessory",
//       "type:keyboard",
//       "segment:creator",
//       "switches:brown",
//       "brand:KeyPro",
//     ],
//     imageUrl: "https://cdn.example.com/images/accessories/p80.jpg",
//   },
//   {
//     id: "p81",
//     name: "Ergonomic Office Mouse",
//     description: "Vertical ergonomic mouse to reduce wrist strain.",
//     price: 2199,
//     currency: "INR",
//     tags: [
//       "category:accessory",
//       "type:mouse",
//       "segment:office",
//       "feature:ergonomic",
//       "brand:OfficeGear",
//     ],
//     imageUrl: "https://cdn.example.com/images/accessories/p81.jpg",
//   },
//   {
//     id: "p82",
//     name: "Webcam 1080p",
//     description: "Full HD webcam with built-in stereo microphone.",
//     price: 2999,
//     currency: "INR",
//     tags: [
//       "category:accessory",
//       "type:webcam",
//       "resolution:1080p",
//       "use:meetings",
//       "brand:BizCam",
//     ],
//     imageUrl: "https://cdn.example.com/images/accessories/p82.jpg",
//   },
//   {
//     id: "p83",
//     name: "Webcam 2K",
//     description: "1440p webcam with auto-focus and low-light correction.",
//     price: 5499,
//     currency: "INR",
//     tags: [
//       "category:accessory",
//       "type:webcam",
//       "resolution:1440p",
//       "segment:premium",
//       "brand:BizCam",
//     ],
//     imageUrl: "https://cdn.example.com/images/accessories/p83.jpg",
//   },
//   {
//     id: "p84",
//     name: "Microphone USB Condenser",
//     description: "USB condenser microphone for podcasts and streaming.",
//     price: 6999,
//     currency: "INR",
//     tags: [
//       "category:audio",
//       "type:microphone",
//       "use:streaming",
//       "segment:creator",
//       "brand:StreamMic",
//     ],
//     imageUrl: "https://cdn.example.com/images/audio/p84.jpg",
//   },
//   {
//     id: "p85",
//     name: 'Ring Light 10"',
//     description:
//       "10-inch ring light with tripod for video calls and content creation.",
//     price: 1999,
//     currency: "INR",
//     tags: [
//       "category:accessory",
//       "type:ring-light",
//       "use:content-creation",
//       "brand:BrightLite",
//     ],
//     imageUrl: "https://cdn.example.com/images/accessories/p85.jpg",
//   },
//   {
//     id: "p86",
//     name: "Laptop Stand Adjustable",
//     description: "Aluminium laptop stand with adjustable height and angle.",
//     price: 1899,
//     currency: "INR",
//     tags: [
//       "category:accessory",
//       "type:laptop-stand",
//       "use:ergonomics",
//       "brand:DeskMate",
//     ],
//     imageUrl: "https://cdn.example.com/images/accessories/p86.jpg",
//   },
//   {
//     id: "p87",
//     name: "Desk Mat XL",
//     description: "Extended desk mat for keyboard and mouse.",
//     price: 1299,
//     currency: "INR",
//     tags: [
//       "category:accessory",
//       "type:desk-mat",
//       "segment:office",
//       "brand:DeskMate",
//     ],
//     imageUrl: "https://cdn.example.com/images/accessories/p87.jpg",
//   },
//   {
//     id: "p88",
//     name: "USB-C Power Adapter 65W",
//     description:
//       "65W USB-C PD charger suitable for laptops and phones.",
//     price: 2999,
//     currency: "INR",
//     tags: [
//       "category:accessory",
//       "type:charger",
//       "power:65W",
//       "connector:usb-c",
//       "brand:ChargeEasy",
//     ],
//     imageUrl: "https://cdn.example.com/images/accessories/p88.jpg",
//   },
//   {
//     id: "p89",
//     name: "USB-C Power Adapter 100W",
//     description: "100W USB-C PD charger with dual ports.",
//     price: 4599,
//     currency: "INR",
//     tags: [
//       "category:accessory",
//       "type:charger",
//       "power:100W",
//       "connector:usb-c",
//       "feature:dual-port",
//       "brand:ChargeEasy",
//     ],
//     imageUrl: "https://cdn.example.com/images/accessories/p89.jpg",
//   },
//   {
//     id: "p90",
//     name: "NVMe SSD 500GB",
//     description:
//       "Internal NVMe SSD with 500GB capacity for laptops and desktops.",
//     price: 3999,
//     currency: "INR",
//     tags: [
//       "category:storage",
//       "type:nvme-ssd",
//       "capacity:500GB",
//       "brand:SpeedDrive",
//     ],
//     imageUrl: "https://cdn.example.com/images/storage/p90.jpg",
//   },
//   {
//     id: "p91",
//     name: "NVMe SSD 1TB",
//     description:
//       "High-speed 1TB NVMe SSD for gaming and creative workloads.",
//     price: 6999,
//     currency: "INR",
//     tags: [
//       "category:storage",
//       "type:nvme-ssd",
//       "capacity:1TB",
//       "segment:gaming",
//       "brand:SpeedDrive",
//     ],
//     imageUrl: "https://cdn.example.com/images/storage/p91.jpg",
//   },
//   {
//     id: "p92",
//     name: "RAM 8GB DDR4",
//     description: "Single 8GB DDR4 RAM stick for laptops.",
//     price: 1999,
//     currency: "INR",
//     tags: [
//       "category:component",
//       "type:ram",
//       "capacity:8GB",
//       "standard:ddr4",
//       "brand:MemPlus",
//     ],
//     imageUrl: "https://cdn.example.com/images/components/p92.jpg",
//   },
//   {
//     id: "p93",
//     name: "RAM 16GB DDR4",
//     description: "Single 16GB DDR4 RAM stick for laptops.",
//     price: 3599,
//     currency: "INR",
//     tags: [
//       "category:component",
//       "type:ram",
//       "capacity:16GB",
//       "standard:ddr4",
//       "brand:MemPlus",
//     ],
//     imageUrl: "https://cdn.example.com/images/components/p93.jpg",
//   },
//   {
//     id: "p94",
//     name: "Wi-Fi 6 USB Adapter",
//     description: "USB Wi-Fi adapter with Wi-Fi 6 support.",
//     price: 2299,
//     currency: "INR",
//     tags: [
//       "category:accessory",
//       "type:wifi-adapter",
//       "standard:wifi6",
//       "brand:NetConnect",
//     ],
//     imageUrl: "https://cdn.example.com/images/accessories/p94.jpg",
//   },
//   {
//     id: "p95",
//     name: "Ethernet USB Adapter",
//     description:
//       "USB to Gigabit Ethernet adapter for laptops without Ethernet port.",
//     price: 1499,
//     currency: "INR",
//     tags: [
//       "category:accessory",
//       "type:ethernet-adapter",
//       "brand:NetConnect",
//     ],
//     imageUrl: "https://cdn.example.com/images/accessories/p95.jpg",
//   },
//   {
//     id: "p96",
//     name: "Cable Organizer Kit",
//     description:
//       "Set of cable clips and sleeves to organize desk cables.",
//     price: 799,
//     currency: "INR",
//     tags: [
//       "category:accessory",
//       "type:cable-management",
//       "brand:DeskMate",
//     ],
//     imageUrl: "https://cdn.example.com/images/accessories/p96.jpg",
//   },
//   {
//     id: "p97",
//     name: "USB-C to HDMI Cable 2m",
//     description:
//       "2-meter USB-C to HDMI cable supporting 4K output.",
//     price: 1299,
//     currency: "INR",
//     tags: [
//       "category:accessory",
//       "type:cable",
//       "connector:usb-c",
//       "connector:hdmi",
//       "resolution:4k",
//       "brand:ConnectPro",
//     ],
//     imageUrl: "https://cdn.example.com/images/accessories/p97.jpg",
//   },
//   {
//     id: "p98",
//     name: "HDMI Cable 4K 3m",
//     description:
//       "3-meter HDMI 2.0 cable supporting 4K 60Hz.",
//     price: 799,
//     currency: "INR",
//     tags: [
//       "category:accessory",
//       "type:cable",
//       "connector:hdmi",
//       "resolution:4k",
//       "length:3m",
//       "brand:ConnectPro",
//     ],
//     imageUrl: "https://cdn.example.com/images/accessories/p98.jpg",
//   },
//   {
//     id: "p99",
//     name: "Surge Protector 6-Socket",
//     description:
//       "6-socket surge protector with USB charging ports.",
//     price: 1999,
//     currency: "INR",
//     tags: [
//       "category:accessory",
//       "type:surge-protector",
//       "sockets:6",
//       "feature:usb-ports",
//       "brand:SafePower",
//     ],
//     imageUrl: "https://cdn.example.com/images/accessories/p99.jpg",
//   },
// ];

;